### ISSUE TITLE
Write and automate test cases for user creation/update and login

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/integrade#12]
We need to write all the test cases for all the new authentication features for REGULAR users.

**Currently I do not see a way to create additional super users via the API other than the one we are assuming exists before running the `integrade` functional tests.**

These include:

## Happy path
See [api user creation docs](https://github.com/cloudigrade/cloudigrade/blob/master/docs/rest-api-examples.rst#user-account-setup)
- [x] Verify that there is a test for user account creation with username and password
- [x] Verify that there is a test checking if an authentication token can be generated for users created with username and password
  - [x] Verify that the authentication token can actually authenticate the request and doing a get request to `/auth/me/` returns proper information.
- [x] Verify that there is a test that changes password using the old one (see [docs](http://djoser.readthedocs.io/en/stable/base_endpoints.html#set-password))
  - [x] Verify that the test ensures the new password can be used to generate an authentication token.
- [x] Verify that there is a test to ensure all current available `/api/v1/*` endpoints can't be accessed with an invalid authentication token.
- [x] Verify that there is a test that destroys an authentication token and the authentication token can't be used anymore to do a request to `/auth/me/` endpoint.

## Negative/edge cases

- [x] Verify that there is a test that attempts to create an user account with missing username, password, ~or email~ and it fails.
    * currently possible to create missing email, but I don't think they **should** be able to do that
- [x] ~Verify that there is a test that attempts to create an user account with an invalid email address? (no @ symbol)~
    * currently no validation, but I think their **should** be

**Comment by kdelee** [comment]
May need to update how client forms url, seeing as the auth stuff all lives at `$CLOUDIGRADE_BASE_URL/auth/` and not at `$CLOUDIGRADE_BASE_URL/api/v1/`

**Comment by elyezer** [comment]
After working on adding the test cases for this issues I have some points that we need to clarify:

* Will cloudigrade support all that authentication and user account management? Like will it support setting email and resetting password or will all that be just temporary and it will integrate authentication and user account management with another system?
* All the endpoints available at /auth/ are provided by djoser and it has good tests for all those, including password reset. That said will we want to include very complete tests for it, like testing password reset and other than just login and logout? I know there are items described on this issue description but I want to re-evaluate those.

With the above I am pretty much trying to find what we are expecting to have and support for user authentication and account management.

@kdelee and @infinitewarp let me know your opinion.

**Comment by elyezer** [comment]
Here is the follow up comment:

Removed:

- Verify we can get a token that allows us to reset password (would be sent to email, see [docs](http://djoser.readthedocs.io/en/stable/base_endpoints.html#reset-password))  (currently blocked by https://github.com/cloudigrade/cloudigrade/issues/288)
  - Created https://github.com/cloudigrade/integrade/issues/18 to track it
- Verify we have GET access to all endpoints that require authentication `/api/v1/account/`, `/api/v1/instances/`, `/api/v1/report/` ([requires params, see api doc](https://github.com/cloudigrade/cloudigrade/blob/master/docs/rest-api-examples.rst#customer-account-setup)) and only see your own stuff
  - so we should create multiple users and create resources associated with them and then double check this
  - Created https://github.com/cloudigrade/integrade/issues/19 to track it
- Verify that super users can get list of all users (see https://github.com/cloudigrade/cloudigrade/issues/279)
 - Created https://github.com/cloudigrade/integrade/issues/20 to track it

**Comment by elyezer** [comment]
I am checking if we will support user account operations related to email. If that is not a thing we will care for now then I will cross them from this issue and we create another when an user story is created on cloudigrade.

**Comment by infinitewarp** [comment]
Regarding your question from two days ago, @elyezer, the overall answer is that all of the authentication we have now is temporary, and we only want enough minimal functionality to work for the pilot launch. I suspect that will include:

- user create (only as super user)
- user activate
- set password
- reset password
- token create (login)
- token destroy (logout)

Several of these haven't been defined anywhere in our UI designs, and it's unclear when exactly we will integrate and verify each of them. There are also some out-of-the-box features we may want to disable (example: deleting your own user), but we also have not planned any of that yet.

You may test each of the Djoser endpoints if you like, but I don't think we should exhaustively test them. Basic smoke testing should be sufficient here.

**Comment by elyezer** [comment]
@infinitewarp thank you for the clarification. With the added tests we are checking the functionality you listed. So think we are fine to get the PR reviewed and move on.

**Comment by kdelee** [comment]
@elyezer I went through the code in pr #17 and you have addressed all items remaining on this issue, so I will close it when the PR is merged :+1: thanks!
