### ISSUE TITLE
Add test for user account's password reset through email

### ISSUE THREAD

**Issue by elyezer** [cloudigrade/integrade#18]
As a Cloudigrade QE, I want to have a test that check if a password reset token is sent to email and it allows changing an user account's password.

## Acceptance Criteria

- [ ] Verify that there is a test for testing user account's password reset through email exists.
- [ ] Verify that the test is performing a password reset request
- [ ] Verify that the test is changing the password to a new one.
- [ ] Verify that the test is ensuring that after the password reset the user can login using the new password. 

### Negative and/or edge cases

- [ ] Verify that there is a test to check if the password reset email can't be sent to a different email other than the one in the user's account requesting the reset. 
- [ ] Verify that there is a test to check if the password reset token sent can't used twice.
- [ ] Verify that there is a test to check if providing a wrong current password during a password reset fail.

## Assumptions and Questions

- Password reset through email will be supported.
- Test infrastructure will allow receiving email.

**Comment by kdelee** [comment]
@elyezer I think this feature got axed

**Comment by elyezer** [comment]
Yes it got axed. We can close this.
