### ISSUE TITLE
Create helper function to power on and off ec2 instances

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/integrade#28]
---

As integrade test developer, I need a way to turn on and off instances from within the test framework. I would like to be able to specify how X many instances, based off of Y AMI, to run for Z seconds. 

Instance activity is only measured beginning at account creation time, therefore instance activity must occur during the life of the test run if we want to measure real live data. 

Tests that do this will probably need to be run on our own resources (i.e. jenkins) because it will take more time. Therefore this feature must be optional, i.e. framework still runs without it.

I will also need to be able to configure integrade to know about what ARN maps to what amazon account # and what AMIs in that account I would like to use for instance creation. I will need to be able to configure credentials for API access (secret key).

I probably also will want to configure known data about the AMIs, like whether they are RHEL, Ubuntu, Windows, etc.

## Acceptance Criteria

- [x] Verify I have a way to configure the test framework to know what AMIs are associated with what AWS account #'s
- [x] Verify I have a way to run X number of instances for Y amount of time based off of an AMI of my choosing.
- [x] Verify I have a mark that helps me skip tests that need this functionality if the necessary configuration is missing.
- [x] Verify other tests still run without necessary config for this feature.
- [x] Verify sensitive information about my access keys etc is not exposed by the helper function if something goes wrong.

## Assumptions and Questions

- I think we are going to want to use boto3 from within python for this
- I think we are going to want to have a config file
- I need to be able to run other tests without this config sometimes

@elyezer what do you think about this

**Comment by elyezer** [comment]
Let's split this into two issues, one to work on the script and the other to work on getting the results from the script and then using from inside the automation framework.

**Comment by kdelee** [comment]
Went with using `~/.aws/config` for configuring various profiles ... but we may want to switch to environment variables if we will be running on travis

**Comment by kdelee** [comment]
I think I will do a follow up PR checking in some of the integrade config files because the information contained is not sensitive (does not grant anyone access to anything), and that way we can share configuration

**Comment by elyezer** [comment]
@kdelee do you want to leave this open until you get the new changes in? Because everything here is already verified and I think we can close this if you don't want to track the new changes here.

**Comment by kdelee** [comment]
Lets close it, as you said, this work is done...more awaits to get my test ready to run on automation, but there are some issues we need to resolve with cloudigrade to get that to happen (message queues need to be purged, cluster needs to be scaled to 0, need to identify what in database must be gone for everything to work, might need to change the timing of how often houndigrade is told to be active.)
