### ISSUE TITLE
Add test to exercise the sysconfig API endpoint 

### ISSUE THREAD

**Issue by elyezer** [cloudigrade/integrade#33]
As a QE, I want a test that exercises the `sysconfig` API endpoint which returns the AWS account information.

## Acceptance Criteria

- [x] Verify there is a test that performs an authenticated GET request to the `sysconfig` API endpoint and assert a 200 status code is returned with content like `{'aws_account_id': <account_id>}`
- [x] Verify that there is a test that checks the endpoint can't be accessed without being logged in.

## Assumptions and Questions

- https://github.com/cloudigrade/cloudigrade/pull/377 should be merged so this issue can be worked on.

**Comment by kdelee** [comment]
verified :)
