### ISSUE TITLE
Add API tests to ensure CloudTrail is automatically configured when adding cloud accounts

### ISSUE THREAD

**Issue by elyezer** [cloudigrade/integrade#36]
As QE, I want tests that ensure CloudTrail is automatically configured when creating a Cloud Account over API.

## Acceptance Criteria

- [x] Verify that there is a test to ensure CloudTrail will be automatically configured when creating the cloud account.
- [x] Verify that there is a test to check if CloudTrail is already setup on the cloud account it will be updated (if possible to check that the CloudTrail config was updated).

## Assumptions and Questions

- The cloud account used on the test should have the policy for cloudigrade configured to allow cloudigrade setup CloudTrail automatically. The actions are: `cloudtrail:{StartLogging,DescribeTrails,CreateTrail,UpdateTrail,PutEventSelectors}`
- If CloudTrail is already setup on the cloud account it will be updated.
- The related user story is https://github.com/cloudigrade/cloudigrade/issues/214
- The test should clean up the CloudTrail using AWS API so that the cloud account can be reused later.

**Comment by kdelee** [comment]
I can do some poking at AWS but also, the end goal is that new instances created after the account is active are discovered, so that will be the real functional test that the CloudTrail work does what was desired.

**Comment by kdelee** [comment]
@elyezer I'm also wondering about what we expect to happen if a customer fatfingers the CloudTrail and deletes it on accident :computer_mouse:  :open_hands:

**Comment by elyezer** [comment]
This is specifically to check if CloudTrail is setup, checking if the system will collect the usage events will be covered by another issue when the feature is ready.

About deleting CloudTrail on accident this is not something that is expected by CLoudigrade but this will be noticed when the report endpoints are done because they will provide the last time an event was received and processed.

**Comment by kdelee** [comment]
1st verfication item covered in basic cloud account creation test https://github.com/cloudigrade/integrade/blob/698ff9e6d6cb181d45c48ad34c4eed3e91711016/integrade/tests/api/v1/test_cloud_accounts.py#L66

2nd verification item covered by new test:
https://github.com/cloudigrade/integrade/blob/698ff9e6d6cb181d45c48ad34c4eed3e91711016/integrade/tests/api/v1/test_cloud_accounts.py#L297

@elyezer can you verfiy can close
