### ISSUE TITLE
Utility function to create user and produce the authentication token + get route

### ISSUE THREAD

**Issue by kdelee** [cloudigrade/integrade#4]
Given we know where cloudigrade is, we need a function that creates the super user and exports the authentication token to an environment variable that test framework can then use later to authenticate with the server.

To do this we need to know:
- Where is the `oc` binary (with sane default)
- Where is the openshift cluster we are talking to?
- What is the OAuth token for the openshift cluster?

Please document how the above are ingested (for example, environment variables)

Verify the following outputs:
- [x] $CLOUDIGRADE_USER=username
- [x] $CLOUDIGRADE_USER_PASS=password
- [x] $CLOUDIGRADE_TOKEN=token *(please just the "2343lkjlkjsaldkjr2j3" part, I will build header later)*
- [x] $CLOUDIGRADE_BASE_URL= what is the route to cloudigrade (just the base url, not `/api/v1`.(domain name only, not http/https)
- [x] $USE_HTTPS=boolean (True/False) --> I will assume false, so no need to set it if it is served over http
- [x] $SSL_VERIFY=boolean(True/False) --> I will assume false, so no need to set it if insecure 

This would be run BEFORE the test framework runs either locally or in automation.

**Comment by ilyavw** [comment]
Demo: Lines 1312 and on: https://travis-ci.org/cloudigrade/integrade/builds/375943805?utm_source=github_status&utm_medium=notification
https://github.com/cloudigrade/integrade/blob/master/.travis.yml#L13
<img width="771" alt="image" src="https://user-images.githubusercontent.com/34514071/39759959-078061ce-52a2-11e8-8044-cbeb9ebd44b1.png">
